# Generated by Django 6.0.5 on 2026-05-22 09:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MonthlyQuota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reference_month', models.DateField(verbose_name='Mes de referencia')),
                ('due_date', models.DateField(verbose_name='Data de vencimento')),
                ('amount_due', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor a pagar')),
                ('status', models.CharField(choices=[('pending', 'Pendente'), ('awaiting_validation', 'Aguarda validacao'), ('paid', 'Paga'), ('overdue', 'Em atraso')], default='pending', max_length=30)),
                ('generated_automatically', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'quota mensal',
                'verbose_name_plural': 'quotas mensais',
                'ordering': ['-reference_month', 'vehicle__plate_number'],
            },
        ),
        migrations.CreateModel(
            name='QuotaConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor da quota')),
                ('late_fee_percentage', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Percentagem de multa')),
                ('effective_from', models.DateField(verbose_name='Vigora a partir de')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'configuracao de quota',
                'verbose_name_plural': 'configuracoes de quota',
                'ordering': ['-effective_from'],
            },
        ),
        migrations.CreateModel(
            name='MemberProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('member_number', models.CharField(max_length=30, unique=True, verbose_name='Numero de associado')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Telefone')),
                ('identity_card', models.CharField(blank=True, max_length=30, verbose_name='BI')),
                ('staff_name', models.CharField(blank=True, max_length=120, verbose_name='Staff')),
                ('role', models.CharField(choices=[('member', 'Associado'), ('treasurer', 'Tesoureiro'), ('admin', 'Administrador')], default='member', max_length=20)),
                ('is_active_member', models.BooleanField(default=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='member_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'perfil de associado',
                'verbose_name_plural': 'perfis de associados',
            },
        ),
        migrations.CreateModel(
            name='PaymentRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('method', models.CharField(choices=[('cash', 'Dinheiro'), ('multicaixa', 'Multicaixa')], max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pendente'), ('simulated', 'Simulado'), ('validated', 'Validado'), ('rejected', 'Rejeitado')], default='pending', max_length=20)),
                ('amount_paid', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor pago')),
                ('payment_date', models.DateTimeField(verbose_name='Data do pagamento')),
                ('simulated_reference', models.CharField(blank=True, max_length=50)),
                ('validated_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, verbose_name='Observacoes')),
                ('quota', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='portal.monthlyquota')),
                ('validated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='validated_payments', to='portal.memberprofile')),
            ],
            options={
                'verbose_name': 'registo de pagamento',
                'verbose_name_plural': 'registos de pagamento',
                'ordering': ['-payment_date'],
            },
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('plate_number', models.CharField(max_length=20, unique=True, verbose_name='Matricula')),
                ('model', models.CharField(max_length=100, verbose_name='Modelo')),
                ('year', models.PositiveIntegerField(verbose_name='Ano')),
                ('color', models.CharField(max_length=50, verbose_name='Cor')),
                ('is_active', models.BooleanField(default=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='vehicles', to='portal.memberprofile')),
            ],
            options={
                'verbose_name': 'veiculo',
                'verbose_name_plural': 'veiculos',
                'ordering': ['plate_number'],
            },
        ),
        migrations.AddField(
            model_name='monthlyquota',
            name='vehicle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='monthly_quotas', to='portal.vehicle'),
        ),
        migrations.AlterUniqueTogether(
            name='monthlyquota',
            unique_together={('vehicle', 'reference_month')},
        ),
    ]
