# Generated by Django 6.0.5 on 2026-05-22 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentrecord',
            name='proof_file',
            field=models.FileField(blank=True, upload_to='payment_proofs/'),
        ),
        migrations.AlterField(
            model_name='paymentrecord',
            name='method',
            field=models.CharField(choices=[('cash', 'Pagamento em maos'), ('bank_transfer', 'Transferencia bancaria')], max_length=20),
        ),
        migrations.AlterField(
            model_name='paymentrecord',
            name='status',
            field=models.CharField(choices=[('pending', 'Pendente'), ('submitted', 'Comprovante submetido'), ('validated', 'Validado'), ('rejected', 'Rejeitado')], default='pending', max_length=20),
        ),
    ]
