# Generated by Django 6.0.5 on 2026-06-22 18:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0002_paymentrecord_proof_file_alter_paymentrecord_method_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='monthlyquota',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='monthlyquota',
            name='vehicle',
        ),
        migrations.AddField(
            model_name='monthlyquota',
            name='member',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='monthly_quotas', to='portal.memberprofile'),
            preserve_default=False,
        ),
        migrations.AlterModelOptions(
            name='monthlyquota',
            options={'ordering': ['-reference_month', 'member__member_number'], 'verbose_name': 'quota mensal', 'verbose_name_plural': 'quotas mensais'},
        ),
        migrations.AlterUniqueTogether(
            name='monthlyquota',
            unique_together={('member', 'reference_month')},
        ),
    ]
