# Generated by Django 6.0.5 on 2026-06-22 18:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0003_alter_monthlyquota_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monthlyquota',
            name='member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='monthly_quotas', to='portal.memberprofile'),
        ),
        migrations.AlterField(
            model_name='paymentrecord',
            name='quota',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='portal.monthlyquota'),
        ),
        migrations.AlterField(
            model_name='paymentrecord',
            name='validated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='validated_payments', to='portal.memberprofile'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehicles', to='portal.memberprofile'),
        ),
    ]
